name: CI/CD CRUD Kesehatan

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy ke EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.24.124.210 << 'EOF'
        cd /var/www/t4
        git config --global --add safe.directory /var/www/t4
        git fetch --all
        git reset --hard origin/main
        sudo systemctl restart nginx
        EOF